mysite/inventory/urls.py
from django.urls import path, include
from .views import *
from django.conf.urls import url

app_name = 'inventory'
urlpatterns = [
    path('', stock, name='stock'),
    path('list', product_list, name='product_list'),
    path('cat/<category_slug>', product_list, name='product_list_by_category'),
    path('c/<slug>', product_list_company, name='product_list_by_company'),
    path('stock/<id>', add_stock, name='add_stock'),
    path('remove/<id>/<ty>', remove_stock, name='remove_stock'),
    path('update/<id>/<ty>', update_stock, name='update_stock'),
    path('delete/<id>', delete_stock, name='delete_stock'),
]

mysite/login/urls.py
from django.urls import path
from .views import *

app_name = 'login'
urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('register', RegisterView.as_view(), name='register'),
    path('cart', cart, name='cart'),
    path('logout', logout, name='logout'),
    path('update<id>', update, name='update'),
    path('delete<id>', delete, name='delete'),
    path('home', home, name='home'),
    path('checkout', checkout, name='checkout'),
    path('bill', bill, name='bill'),
    path('confirm', confirm, name='confirm'),
    path('charge', charge, name='charge'),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import index

urlpatterns = [
    path('', index),
    path('login/', include('login.urls')),
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('company/', include('company.urls')),
    path('inventory/', include('inventory.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/login/models.py
from django.db import models
from datetime import datetime
from company.models import Product
from django.urls import reverse


class Register(models.Model):
    Fullname = models.CharField(max_length=50)
    email = models.CharField(max_length=80, unique=True)
    password = models.CharField(max_length=15)
    phone = models.CharField(max_length=20)
    register_date = models.DateTimeField(default=datetime.now, blank=True)
    image = models.ImageField(upload_to="user/%Y/%m/%d", blank=True)

    def __str__(self):
        return self.Fullname


class Cart(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, default=None)
    customer = models.ForeignKey(Register, on_delete=models.CASCADE, default=None)
    Quantity = models.IntegerField(default=1)

    def __str__(self):
        return self.product.name

    def update(self):
        return reverse('login:update', args=[self.id])

    def deleteQuery(self):
        return reverse('login:delete', args=[self.id])

    def checkout(self):
        return reverse('login:checkout')

class Bill(models.Model):
    name = models.CharField(max_length=50)
    date = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return str(self.id)

class Log(models.Model):
    bill_id = models.IntegerField(default=0)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, default=None)
    Quantity = models.IntegerField(default=1)

mysite/login/forms.py
from django import forms


class RegisterForm(forms.Form):
    img = forms.FileField(label='')
    name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'login-inputname', 'placeholder': 'Full Name'}), label='')
    email = forms.CharField(widget=forms.EmailInput(
        attrs={'class': 'login-inputname', 'placeholder': 'Email'}), label='')
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'login-inputname', 'placeholder': 'Password'}), label='')
    repassword = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'login-inputname', 'placeholder': 'Confirm PAssword'}), label='')
    phone_no = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'login-inputname', 'placeholder': '+91 9999999'}), label='')


class LoginForm(forms.Form):
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'login-inputname','placeholder':'Email'}), label='')
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'login-inputname', 'placeholder':'Password'}), label='')


class CartForm(forms.Form):
    quantity = forms.IntegerField(label='quantity', min_value=1, max_value=10)

mysite/login/views.py
from django.views import generic
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from inventory.models import *
from .forms import RegisterForm, LoginForm
from django.conf import settings
import stripe


class HomeView(generic.TemplateView):
    template_name = "login/login.html"

    def get(self, request):
        form = LoginForm()
        return render(request, self.template_name)


class LoginView(generic.TemplateView):
    model = Register
    template_name = "login/login.html"

    form = LoginForm()

    def get(self, request):
        if request.session.has_key('username'):
            username = request.session['username']
            q1 = Register.objects.get(email=username)
            q2 = Cart.objects.filter(customer_id=q1.id).count()
            image = q1.image
            request.session['cart_items'] = q2
            return render(request, 'company/product/list.html', {"username": username, 'image': image})
        return render(request, self.template_name, context={'form': self.form})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():

            # username = request.POST['Username']
            # password = request.POST['password']
            username = form.cleaned_data['email']
            password = form.cleaned_data['password']

            try:
                q1 = Register.objects.get(email=username)
            except:
                return render(request, self.template_name, {'error': "User did not exist", 'form': form})
            request.session['username'] = username
            if password == q1.password:
                q2 = Cart.objects.filter(customer_id=q1.id).count()
                request.session['cart_items'] = q2
                return render(request, 'company/product/list.html', {"username": username})
            else:
                msg = "Please enter correct Password"
                return render(request, self.template_name, {'error': msg, 'form': form})


class RegisterView(generic.TemplateView):
    model = Register
    template_name = "login/register.html"

    def get(self, request):
        form = RegisterForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            repassword = form.cleaned_data['repassword']
            phone_no = form.cleaned_data['phone_no']
            img = form.cleaned_data['img']
            q1 = None
            try:
                q1 = Register.objects.filter(email=email).get()
            except:
                pass

            if q1 is not None:
                msg = "User already exist....."
                args = {'form': form, 'error': msg}
                return render(request, self.template_name, args)
            else:
                if password == repassword:
                    Reg = Register(Fullname=name, email=email, password=password, phone=phone_no, image=img)
                    Reg.save()
                    home = HomeView()
                    return redirect('login:login')
                else:
                    msg = "Please enter correct password"
                    args = {'form': form, 'error': msg}
                    return render(request, self.template_name, args)
        else:
            return HttpResponse("Error")


def reg(request):
    return HttpResponse("hello")


def logout(request):
    request.session.flush()
    return redirect("login:login")


def cart(request):
    q1 = Register.objects.get(email=request.session['username'])
    q2 = Cart.objects.filter(customer_id=q1.id)
    image = q1.image
    context = {
        'item': q2,
        'image': image
    }
    return render(request, 'login/cart.html', context=context)


def update(request, id):
    q1 = Cart.objects.get(id=id)
    q1.Quantity = 10
    q1.save()
    return redirect("login:cart")


def delete(request, id):
    q1 = Cart.objects.get(id=id)
    q1.delete()
    request.session['cart_items'] -= 1
    return redirect("login:cart")


def home(request):
    q1 = Bill.objects.filter(name=request.session['username'])
    user = Register.objects.get(email=request.session['username'])
    a = []
    b = LogInventory.objects.filter(user= user)
    for i in q1:
        q2 = Log.objects.filter(bill_id=i.id)
        a+=[j for j in q2]
    return render(request, 'profile1.html', {'data': a, 'user': user, 'data1':b})


def checkout(request):
    q1 = Register.objects.get(email=request.session['username'])
    q2 = Cart.objects.filter(customer_id=q1.id)
    ob = Bill(name=request.session['username'])
    ob.save()
    request.session['number'] = ob.id
    total = 0
    for i in q2:
        total += i.Quantity * i.product.price
        q = Log(bill_id=ob.id, product=i.product, Quantity=i.Quantity)
        q.save()
        i.delete()
    request.session['total'] = total*100
    request.session['cart_items'] = 0
    return redirect('login:confirm')

def confirm(request):
    context = {'key': settings.STRIPE_PUBLISHABLE_KEY, 'amount': request.session['total']}
    return render(request, 'confirm.html', context)

def charge(request):
    if request.method == 'POST':
        stripe.api_key = settings.STRIPE_SECRET_KEY
        charge = stripe.Charge.create(
            amount=int(request.session['total']),
            currency='inr',
            description='A Django charge',
            source=request.POST['stripeToken']
        )
        return redirect('login:bill')

def bill(request):
    id = request.session['number']
    bill = Bill.objects.get(id=id)
    q1 = Log.objects.filter(bill_id=id)
    q2 = Register.objects.get(email=request.session['username'])
    context = {
        'items': q1,
        'invoice': id,
        'name': q2.Fullname,
        'email': q2.email,
        'phone': q2.phone,
        'date': bill.date,
        'total': request.session['total']/100,
    }
    return render(request, 'invoice.html', context=context)

mysite/login/templates/confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'login:charge' %}" method="post">
  {% csrf_token %}
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="{{ key }}"
          data-description="A Django Charge"
          data-amount="{{ amount }}"
          data-locale="auto"></script>
</form>
</body>
</html>

mysite/login/templates/invoice.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>invoice</title>

    <style>
    .invoice-box {
        max-width: 800px;
        margin: auto;
        padding: 30px;
        border: 1px solid #eee;
        box-shadow: 0 0 10px rgba(0, 0, 0, .15);
        font-size: 16px;
        line-height: 24px;
        font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
        color: #555;
    }

    .invoice-box table {
        width: 100%;
        line-height: inherit;
        text-align: left;
    }

    .invoice-box table td {
        padding: 5px;
        vertical-align: top;
    }

    .invoice-box table tr td:nth-child(2) {
        text-align: right;
    }

    .invoice-box table tr.top table td {
        padding-bottom: 20px;
    }

    .invoice-box table tr.top table td.title {
        font-size: 45px;
        line-height: 45px;
        color: #333;
    }

    .invoice-box table tr.information table td {
        padding-bottom: 40px;
    }

    .invoice-box table tr.heading td {
        background: #eee;
        border-bottom: 1px solid #ddd;
        font-weight: bold;
    }

    .invoice-box table tr.details td {
        padding-bottom: 20px;
    }

    .invoice-box table tr.item td{
        border-bottom: 1px solid #eee;
    }

    .invoice-box table tr.item.last td {
        border-bottom: none;
    }

    .invoice-box table tr.total td:nth-child(2) {
        border-top: 2px solid #eee;
        font-weight: bold;
    }

    @media only screen and (max-width: 600px) {
        .invoice-box table tr.top table td {
            width: 100%;
            display: block;
            text-align: center;
        }

        .invoice-box table tr.information table td {
            width: 100%;
            display: block;
            text-align: center;
        }
    }

    /** RTL **/
    .rtl {
        direction: rtl;
        font-family: Tahoma, 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
    }

    .rtl table {
        text-align: right;
    }

    .rtl table tr td:nth-child(2) {
        text-align: left;
    }
    </style>
</head>
{% load static %}
<body>
    <div class="invoice-box">
        <table cellpadding="0" cellspacing="0">
            <tr class="top">
                <td colspan="2">
                    <table>
                        <tr>
                            <td class="title">
                                <img src="{% static 'img/logo.png' %}" style="width:100%; max-width:300px;">
                            </td>
                            <td>
                                Invoice #: {{invoice}}<br>
                                Created: {{date}}<br>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr class="information">
                <td colspan="2">
                    <table>
                        <tr>
                            <td>
                                A.I. Solutions<br>
                                12345 Sunny Road<br>
                                Sunnyville, CA 12345
                            </td>

                            <td>
                                {{name}}<br>
                                {{email}}<br>
                                {{phone}}
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr class="heading">
                <td>Item</td>
                <td>Price</td>
            </tr>
            {% for i in items %}
            <tr class="item">
                <td>{{ i.product.name }}</td>
                <td>{{i.Quantity}} X {{i.product.price}}</td>
            </tr>
            {% endfor %}
            <tr class="total">
                <td></td>

                <td>
                   Total: {{total}}
                </td>
            </tr>
        </table>
    </div>
</body>
</html>

mysite/login/templates/profile.html
{% extends 'base.html' %}
{% block content %}
{% for i in data %}
<b>{{i.Quantity}}</b> X {{i.product.name}}
    <br>
    {% endfor %}
{% endblock %}

mysite/login/templates/profile1.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Profile-{{request.session.username}}{% endblock %}
{% block styles %}
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto'>
  <style>
    h1,h2,h3,h4,h5,h6 {font-family: "Roboto", sans-serif}
    .tab button {
      display: block;
      background-color: inherit;
      color: black;
      padding: 22px 16px;
      width: 100%;
      border: none;
      outline: none;
      text-align: left;
      cursor: pointer;
      transition: 0.3s;
      font-size: 17px;
    }
    .tab button:hover {
      background-color: #ddd;
    }

    /* Create an active/current "tab button" class */
    .tab button.active {
      background-color: #ccc;
    }

    /* Style the tab content */
    .tabcontent {
      padding: 0px 12px;
      border: 1px solid #ccc;
      border: none;
      min-height: 300px;
    }
  </style>
{% endblock %}
{% block content %}
<div class="w3-light-grey">
<div class="w3-content w3-margin-top" style="max-width:1400px;">
  <div class="w3-row-padding">
    <div class="w3-third">
      <div class="w3-white w3-text-grey w3-card-4">
        <div class="w3-display-container">
          <img src="{% if user.image %} {{ user.image.url }}
                  {% else %} {% static 'img/default.jpg' %} {% endif %}" style="width:100%" alt="Avatar">
          <div class="w3-display-bottomleft w3-container w3-text-black">
            <h2>{{ user.Fullname }}</h2>
          </div>
        </div>
        <div class="w3-container">
          <br>
          <p><i class="fa fa-envelope fa-fw w3-margin-right w3-large w3-text-teal"></i>{{ user.email }}</p>
          <p><i class="fa fa-phone fa-fw w3-margin-right w3-large w3-text-teal"></i>{{ user.phone }}</p>
          <hr>
          <p class="w3-large"><b><i class="fa fa-asterisk fa-fw w3-margin-right w3-text-teal"></i>Inventory Management</b></p>
          <div class="tab">
            <button class="tablinks" onclick="openCity(event, 'London')" id="defaultOpen">Purchase History</button>
            <button class="tablinks" onclick="openCity(event, 'Paris')">Inventory Log</button>
            <button class="tablinks" onclick="openCity(event, 'Tokyo')">Administrate</button>
          </div>
        </div>
      </div>
      <br>
    </div>
    <div class="w3-twothird">
      <div class="w3-container w3-card w3-white w3-margin-bottom">

        <div id="London" class="tabcontent">
          <h3>Purchase History</h3>
          <table border="2px" width="100%">
            <tr>
              <th>Bill-ID</th>
              <th>Product Name</th>
              <th>Quantity</th>
            </tr>
            {% for i in data %}
              <tr>
                <td>{{i.bill_id}}</td>
                <td><a href="{{i.product.get_absolute_url}}">{{i.product.name}}</a></td>
                <td>{{i.Quantity}}</td>
              </tr>
            {% endfor %}
          </table>
        </div>

        <div id="Paris" class="tabcontent">
          <h3>Inventory Log</h3>
          <table border="2px" width="100%">
            <tr>
              <th>Product Name</th>
              <th>Product Quantity</th>
              <th>Operation</th>
              <th>Timestamp</th>
            </tr>
            {% for i in data1 %}
              <tr>
                <td><a href="{{i.product.get_absolute_url}}">{{i.product.name}}</a></td>
                <td>{{i.quantity}}</td>
                <td>{{i.operation}}</td>
                <td>{{i.timestamp}}</td>
              </tr>
            {% endfor %}
          </table>
        </div>

        <div id="Tokyo" class="tabcontent">
          <h3>Administrate</h3>
          <br><br>
          <a href="{% url 'inventory:stock' %}"><button type="button" class="btn btn-primary">View Inventory</button></a>
          <br><br>
          <a href="{% url 'inventory:product_list' %}"><button type="button" class="btn btn-primary">Browse Product</button></a>
        </div>
      </div>
    </div>
  </div>
</div>
    <br><br>
</div>
      <script>
        function openCity(evt, cityName) {
          var i, tabcontent, tablinks;
          tabcontent = document.getElementsByClassName("tabcontent");
          for (i = 0; i < tabcontent.length; i++) {
            tabcontent[i].style.display = "none";
          }
          tablinks = document.getElementsByClassName("tablinks");
          for (i = 0; i < tablinks.length; i++) {
            tablinks[i].className = tablinks[i].className.replace(" active", "");
          }
          document.getElementById(cityName).style.display = "block";
          evt.currentTarget.className += " active";
        }

        // Get the element with id="defaultOpen" and click on it
        document.getElementById("defaultOpen").click();
      </script>
{% endblock %}