mysite/company/urls.py
from django.conf.urls import url
from django.urls import path

from .views import *

app_name = 'company'

urlpatterns = [
    url(r'^$', product_list, name='product_list'),
    path('your_name/', get_name),
    url(r'^(?P<category_slug>[-\w]+)/$', product_list, name='product_list_by_category'),
    path('c/<slug>', product_list_company, name='product_list_by_company'),
    path('comp/<slug>', company_detail, name='company_detail'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', product_detail, name='product_detail'),
    path('cart/<slug>-<id>', add_cart, name='add_cart')
]

mysite/inventory/urls.py
from django.urls import path, include
from .views import *
from django.conf.urls import url

app_name = 'inventory'
urlpatterns = [
    path('', stock, name='stock'),
    path('list', product_list, name='product_list'),
    path('cat/<category_slug>', product_list, name='product_list_by_category'),
    path('c/<slug>', product_list_company, name='product_list_by_company'),
    path('stock/<id>', add_stock, name='add_stock'),
    path('remove/<id>/<ty>', remove_stock, name='remove_stock'),
    path('update/<id>/<ty>', update_stock, name='update_stock'),
    path('delete/<id>', delete_stock, name='delete_stock'),
]

mysite/login/urls.py
from django.urls import path
from .views import *

app_name = 'login'
urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('register', RegisterView.as_view(), name='register'),
    path('cart', cart, name='cart'),
    path('logout', logout, name='logout'),
    path('update<id>', update, name='update'),
    path('delete<id>', delete, name='delete'),
    path('home', home, name='home'),
    path('checkout', checkout, name='checkout'),
    path('bill', bill, name='bill'),
    path('confirm', confirm, name='confirm'),
    path('charge', charge, name='charge'),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import index

urlpatterns = [
    path('', index),
    path('login/', include('login.urls')),
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('company/', include('company.urls')),
    path('inventory/', include('inventory.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/inventory/models.py
from django.db import models
from login.models import Register, Product
from django.urls import reverse

class Stocks(models.Model):
    user = models.ForeignKey(Register, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)

    def __str__(self):
        return str(self.product.name)

    def remove(self):
        return reverse('inventory:remove_stock', args=[self.id, 'remove'])
    def add(self):
        return reverse('inventory:remove_stock', args=[self.id, 'add'])
    def dele(self):
        return reverse('inventory:delete_stock', args=[self.id])


class LogInventory(models.Model):
    user = models.ForeignKey(Register, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    operation = models.CharField(max_length=10)
    timestamp = models.DateTimeField(auto_now_add=True)

mysite/inventory/views.py
from django.shortcuts import render
from django.http import HttpResponse
from company.models import *
from login.models import *
from django.shortcuts import render, get_object_or_404, redirect
from .models import *

def delete_stock(request, id):
    q1 = Stocks.objects.get(id=id)
    q1.delete()
    q2 = LogInventory(user=q1.user, product=q1.product, quantity=q1.quantity, operation='DELETE')
    q2.save()
    return redirect('inventory:stock')


def stock(request):
    user = Register.objects.get(email=request.session['username'])
    q1 = Stocks.objects.filter(user=user)
    return render(request, 'inventory/home.html', {'stock': q1})

def add_stock(request, id):
    if request.method == 'POST':
        quantity = request.POST['quantity']

    product = Product.objects.get(id=id)
    customer = request.session['username']
    customer = Register.objects.get(email=customer)
    q1 = None
    try:
        q1 = Stocks.objects.get(product=product)
    except:
        pass

    if q1:
        q1.quantity += int(quantity)
        q1.save()
    else:
        Stock = Stocks(product=product, user=customer, quantity=quantity)
        Stock.save()
    q2 = LogInventory(user=customer, product=product, quantity=quantity, operation='STOCKIN')
    q2.save()
    return redirect('inventory:product_list')

def product_list_company(request, slug=None):
    category = None
    company = None
    q1 = Register.objects.get(email=request.session['username'])
    image = q1.image
    categories = Category.objects.all()
    companies = Company.objects.all()
    products = Product.objects.filter(available=True)
    if slug:
        company = get_object_or_404(Company, slug=slug)
        products = Product.objects.filter(company=company)
    context = {
        'category': category,
        'categories': categories,
        'products': products,
        'companies': companies,
        'company': company,
        'image':image
    }
    return render(request, 'inventory/list.html', context)

def product_list(request, category_slug=None):
    q1 = Register.objects.get(email=request.session['username'])
    image = q1.image
    category = None
    company = None
    categories = Category.objects.all()
    companies = Company.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)

    context = {
        'category': category,
        'categories': categories,
        'products': products,
        'companies': companies,
        'company': company,
        'image': image
    }
    return render(request, 'inventory/list.html', context)

def remove_stock(request, id, ty):
    q1 = Stocks.objects.get(id=id)
    return render(request, 'inventory/edit.html', context={'stock': q1, 'ty':ty})

def update_stock(request, id, ty):
    q1 = Stocks.objects.get(id=id)
    customer = request.session['username']
    customer = Register.objects.get(email=customer)
    product = q1.product
    quantity = request.POST['quantity']
    if ty == 'remove':
        q1.quantity -= int(quantity)
        opr = 'STOCKOUT'

    elif ty == 'add':
        q1.quantity += int(quantity)
        opr = 'STOCKIN'
    q1.save()
    q2 = LogInventory(user=customer, product=product, quantity=quantity, operation=opr)
    q2.save()
    return redirect('inventory:stock')

mysite/inventory/templates/inventory/edit.html
{% extends 'base.html' %}
{% load static %}
{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles/card.css' %}" />
{% endblock %}
{% block content %}
    <div class="row list-container">
        <div class="text-center">
            <div class="card-body">
                <div><img src="{% if stock.product.image %} {{ stock.product.image.url }}
                  {% else %} {% static 'img/default.jpg' %} {% endif %}" class="image"></div>
                <div class="card-heading">{{ stock.product.name }}</div>
                <a href="{{ stock.product.category.get_absolute_url }}" class="click-btn" target="_blank">Category: {{ stock.product.category }}</a>
                <a href="{{ stock.product.company.get_absolute_url }}" class="click-btn" target="_blank">Company: {{ stock.product.company }}</a>
                <br><br>
                <form action="/inventory/update/{{ stock.id }}/{{ty}}" method="post">
                  {% csrf_token %}
                  <input type="number" name="quantity">
                  <input type="submit" value="Update" class="click-btn">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

mysite/inventory/templates/inventory/home.html
{% extends 'base.html' %}
{% block styles %}
    <style>
        table {
          border-collapse: collapse;
          border-spacing: 0;
          width: 100%;
          border: 1px solid black;
        }

        th, td {
          text-align: left;
          padding: 10px;
        }

        tr:nth-child(even){background-color: #f2f2f2}
    </style>
{% endblock %}
{% block content %}
    <div style="overflow-x:auto;">
        <table border="5px">
            <tr>
                <th>Product Name</th>
                <th>Quantity</th>
                <th>Operations</th>
            </tr>
            {% for i in stock %}
                <tr>
                    <td><a href="{{i.product.get_absolute_url}}">{{ i.product.name }}</a></td>
                    <td>{{ i.quantity }}</td>
                    <td>
                        <a href="{{ i.remove }}"><button type="button" class="btn btn-primary">StockOUT</button></a>
                        <a href="{{ i.add }}"><button type="button" class="btn btn-primary">StockIN</button></a>
                        <a href="{{ i.dele }}"><button type="button" class="btn btn-primary">Delete</button></a>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

mysite/inventory/templates/inventory/list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }} {% else %} Products {% endif %}
{% endblock %}
{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles/card.css' %}" />
{% endblock %}
{% block content %}
   <div class="container-fluid">
      <div class="row">
        <div class="col-sm-8 blog-main">
          <div class="blog-post">
              <div class="row">
                  {% for product in products %}
                  <div class="col-lg-4 col-md6 col-sm-12 text-center">
                    <div class="card-body">
                        <div><img src="{% if product.image %} {{ product.image.url }}
                            {% else %} {% static 'img/default.jpg' %} {% endif %}" class="image"></div>
                        <div class="card-heading">{{ product.name }}</div>
                        <div class="card-wrapper">Rs. {{ product.price }}</div>
                        <form action="{{product.add_stock}}" method="post" onsubmit="alert('Added Successfully')">
                          {% csrf_token %}
                          <input type="text" name="quantity">
                          <i class="fa fa-shopping-cart" style="font-size:24px"></i>
                          <input type="submit" value="Add to Stock" class="click-btn">
                        </form>
                    </div>
                  </div>
                  {% endfor %}
              </div>
          </div><!-- /.blog-post -->
        </div><!-- /.blog-main -->
        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
            <div class="card-body">
                <div class="card-heading">Categories</div>
                <div class="card-wrapper">
                    <ol class="list-unstyled">
                        <li {% if not category %} class="active"{% endif %}><a href="{% url 'company:product_list' %}">All</a></li>
                        {% for c in categories %}
                            <li {% if category.slug == c.slug %} class="active"{% endif %}>
                                <a href="{{ c.inventory }}">{{ c.name }}</a>
                            </li>
                        {% endfor %}
                    </ol>
                </div>
                <div class="card-heading">Companies</div>
                <div class="card-wrapper">
                    <ol class="list-unstyled">
                        <li {% if not category %} class="active"{% endif %}><a href="{% url 'company:product_list' %}">All</a></li>
                        {% for c in companies %}
                        <li {% if category.slug == c.slug %} class="active"{% endif %}>
                            <a href="{{ c.inventory }}">{{ c.name }}</a>
                        </li>
                        {% endfor %}
                    </ol>
                </div>
            </div>
          </div><!-- /.blog-sidebar -->
        </div><!-- /.row -->
      </div><!-- /.container -->
  {% endblock %}