mysite/company/urls.py
from django.conf.urls import url
from django.urls import path

from .views import *

app_name = 'company'

urlpatterns = [
    url(r'^$', product_list, name='product_list'),
    path('your_name/', get_name),
    url(r'^(?P<category_slug>[-\w]+)/$', product_list, name='product_list_by_category'),
    path('c/<slug>', product_list_company, name='product_list_by_company'),
    path('comp/<slug>', company_detail, name='company_detail'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', product_detail, name='product_detail'),
    path('cart/<slug>-<id>', add_cart, name='add_cart')
]

mysite/login/urls.py
from django.urls import path
from .views import *

app_name = 'login'
urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('register', RegisterView.as_view(), name='register'),
    path('cart', cart, name='cart'),
    path('logout', logout, name='logout'),
    path('update<id>', update, name='update'),
    path('delete<id>', delete, name='delete'),
    path('home', home, name='home'),
    path('checkout', checkout, name='checkout'),
    path('bill', bill, name='bill'),
    path('confirm', confirm, name='confirm'),
    path('charge', charge, name='charge'),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import index

urlpatterns = [
    path('', index),
    path('login/', include('login.urls')),
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('company/', include('company.urls')),
    path('inventory/', include('inventory.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/company/models.py
from django.db import models
from django.urls import reverse

class Company(models.Model):
    name = models.CharField(max_length=150)
    slug = models.SlugField(max_length=150, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('company:company_detail', args=[self.slug])

    def get_absolute_url_cat(self):
        return reverse('company:product_list_by_company', args=[self.slug])

    def inventory(self):
        return reverse('inventory:product_list_by_company', args=[self.slug])


class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True, db_index=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('company:product_list_by_category', args=[self.slug])
    def inventory(self):
        return reverse('inventory:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=150, db_index=True, unique=True)
    description = models.TextField(blank=True)
    price = models.IntegerField(default=1500)
    available = models.BooleanField(blank=True)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('company:product_detail', args=[self.id, self.slug])

    def add_cart(self):
        return reverse('company:add_cart', args=[self.slug, self.id])
    def add_stock(self):
        return reverse('inventory:add_stock', args=[self.id])

mysite/company/forms.py
from django import forms

class NameForm(forms.Form):
    your_name = forms.IntegerField(label='Quantity ', min_value=1, max_value=50)

mysite/company/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect

from .models import *
from login.models import *
from django.shortcuts import render

from .forms import NameForm

def get_name(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = NameForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponse(form.cleaned_data['your_name']+ str(form.cleaned_data['number']))

    # if a GET (or any other method) we'll create a blank form
    else:
        form = NameForm()

    return render(request, 'name.html', {'form': form})


def index(request):
    return HttpResponse("<h1>hello you are in company app")

def product_list(request, category_slug=None):
    q1 = Register.objects.get(email=request.session['username'])
    image = q1.image
    category = None
    company = None
    categories = Category.objects.all()
    companies = Company.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)
    context = {
        'category': category,
        'categories': categories,
        'products': products,
        'companies': companies,
        'company': company,
        'image': image
    }
    return render(request, 'company/product/list.html', context)


def product_list_company(request, slug=None):
    category = None
    company = None
    q1 = Register.objects.get(email=request.session['username'])
    image = q1.image
    categories = Category.objects.all()
    companies = Company.objects.all()
    products = Product.objects.filter(available=True)
    if slug:
        company = get_object_or_404(Company, slug=slug)
        products = Product.objects.filter(company=company)
    context = {
        'category': category,
        'categories': categories,
        'products': products,
        'companies': companies,
        'company': company,
        'image':image
    }
    return render(request, 'company/product/list.html', context)

def product_detail(request, id, slug):
    q1 = Register.objects.get(email=request.session['username'])
    image = q1.image
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    form = NameForm()
    quantity = [i for i in range(1, product.stock + 1)]
    context = {
        'product': product,
        'quantity': quantity,
        'form': form,
        'image':image
    }

    # return render(request, 'name.html', {'form': form})
    return render(request, 'company/product/detail.html', context)

def company_detail(request, slug):
    q1 = Register.objects.get(email=request.session['username'])
    image = q1.image
    company = get_object_or_404(Company, slug=slug)
    context = {
        'company': company,
        'image': image,
    }
    return render(request, 'company/product/cdetail.html', context)

def add_cart(request, id, slug):
    if request.method == 'POST':
        form = NameForm(request.POST)
        if form.is_valid():
            quantity = form.cleaned_data['your_name']

    product = Product.objects.get(id=id)
    customer = request.session['username']
    customer = Register.objects.get(email=customer)
    cart = Cart(product=product, customer=customer, Quantity=quantity)
    cart.save()
    q2 = Cart.objects.filter(customer_id=customer.id).count()
    request.session['cart_items'] = q2
    return redirect('login:cart')

mysite/company/templates/base.html
<!DOCTYPE html>
<html>
  <head>
	<title>{%block title%}{%endblock%}</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    {% load static %}
    <link rel="icon" type="image" href="{% static 'img/default.jpg' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/styles.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'styles/bootstrap.css' %}" />
	{%block script%}{%endblock%}
	{%block styles%}{%endblock%}
  </head>
  <body>
    <header>
    {% if  request.session.username %}
	  <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/company" target="_self">Home</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="about" target="_blank">About</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="contact-us" target="_blank">Contact Us</a>
          </li>
        </ul>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav my-2 my-lg-0">
            <li class="nav-item">
             <a href="{% url 'login:cart' %}" class="nav-link" id="CART">
               <i class="fa fa-shopping-cart" style="font-size:24px">{{request.session.cart_items}}</i>
             </a>
            </li>
          </ul>
          <span class="nav-item dropdown active">
            <span class="nav-link dropdown-toggle" style="color:#fff;" id="navbarDropdown" role="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <img src="{% if image %} {{ image.url }}
                  {% else %} {% static 'img/default.jpg' %} {% endif %}" style="height:25px; width:25px; border-radius:51%;">
            </span>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'login:home' %}">{{request.session.username}}</a>
              <a class="dropdown-item" href="{% url 'login:logout' %}">Logout</a>
            </div>
          </span>
        </div>
      </nav>
    {% else %}
      <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'login:login' %}" target="_self">Home</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="about" target="_blank">About</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="contact-us" target="_blank">Contact Us</a>
          </li>
        </ul>
      </nav>
    {% endif %}
    </header>
    		{%block body%}{%endblock%}
    {% block content %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  </body>
</html>

mysite/company/templates/landing.html
{% extends 'base.html' %}
{% block title %}A.I. Solutions{% endblock %}
{% load static %}
 {% block styles %}
<style>
        body, html {
      height: 100%;
      margin: 0;
      font-family: Arial, Helvetica, sans-serif;
    }

    * {
      box-sizing: border-box;
    }

    .bg-image {
      /* Full height */
      height: 100%;
      /* Center and scale the image nicely */
      background-position: center;
      background-repeat: no-repeat;
      background-size: cover;
    }

    /* Images used */
    .img1 { background-image: url("{% static 'img/art.jpg' %}"); }
    .img2 { background-image: url("{% static 'img/classmatenotebook.png' %}"); }
    .img3 { background-image: url("{% static 'img/classmate.png' %}"); }
    .img4 { background-image: url("{% static 'img/pencils.jpg' %}"); }
    .img5 { background-image: url("{% static 'img/pens.jpg' %}"); }
    .img6 { background-image: url("{% static 'img/puzzles.jpg' %}"); }

    /* Position text in the middle of the page/image */
    .bg-text {
      background-color: rgb(0,0,0); /* Fallback color */
      background-color: rgba(0,0,0, 0.4); /* Black w/opacity/see-through */
      color: white;
      font-weight: bold;
      font-size: 80px;
      border: 10px solid #f1f1f1;
      position: fixed; /* Stay fixed */
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      z-index: 2;
      width: 500px;
      padding: 20px;
      text-align: center;
    }
</style>
    {% endblock %}
{% block body %}
    <div class="bg-image img1"></div>
    <div class="bg-image img2"></div>
    <div class="bg-image img3"></div>
    <div class="bg-image img4"></div>
    <div class="bg-image img5"></div>
    <div class="bg-image img6"></div>
    <a href="/company"><div class="bg-text">A.I. Solutions</div></a>
{% endblock %}

mysite/company/templates/name.html
<form action="/company/your_name/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>